export const dataLoadingPersonaPhases = [
    "BOOM! Unleashing the Perfect Name",
    "Igniting Age with Passion",
    "Crafting Upbringing for Greatness",
    "Sparking Interests with Thrilling Flames",
    "Forging a Career Path with Unstoppable Fire",
    "Illuminating Personality with Vibrant Energy",
    "Fanning the Flames of Aspirations and Goals",
    "Embarking on an Epic Journey of Success",
    "Channeling Inner Strength and Power",
    "Unleashing Creative Brilliance with a Bang",
    "Pioneering Innovation with Unmatched Zeal",
    "Igniting the Spirit of Fearless Adventure",
    "Crafting a Legacy of Bold Achievements",
    "Fueling Ambitions with Unstoppable Momentum",
    "Igniting Passion and Inspiring Greatness",
    "Harnessing the Power of Limitless Imagination",
    "Elevating Dreams to Dazzling Heights",
]